openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: API for user registration, login, and profile management.

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistration"
      responses:
        "200":
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request

  /login:
    post:
      summary: Login with phone number and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad request

  /profile:
    get:
      summary: Get user profile
      security:
        - BearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "403":
          description: Forbidden
    put:
      summary: Update user profile
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfileUpdate"
      responses:
        "200":
          description: Profile updated successfully
        "403":
          description: Forbidden

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        phone_number:
          type: string
        full_name:
          type: string
      required:
        - id
        - phone_number
        - full_name
    UserRegistration:
      type: object
      properties:
        phone_number:
          type: string
        full_name:
          type: string
        password:
          type: string
      required:
        - phone_number
        - full_name
        - password
